# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Chaman Singh
title: Backend Developer (Java-Spring/Spring-Boot)
email: chamangujjar162@gmail.com
website: https://chamangurjar.github.io/chaman-singh/

# Social links
twitter_username: chamangurjar
github_username:  chamangurjar
linkedin_username: singh-chaman
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Chaman Singh and I'm a Backend Developer. Also having experience in iOS and Android Development from scratch to make app live (in play store or app store).

  I am most skilled in:
     - Backend = <u>Java</u>, <u>Spring</u>, <u>Spring-Boot</u>
     - iOS App Development = <mark>iOS (Swift)</mark>
     - Android App Developement = <mark>Android (Java And Kotlin)</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
